version: '3.8'
services:
  app:
    image: node:14
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=production
      - SECRET='HAD_MZW@'
      - DB_HOST=postgres.railway.internal
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=KFjQviXLOUaZSLTCQJbVdNKmWzxnCAnJ
      - DB_NAME=railway
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KFjQviXLOUaZSLTCQJbVdNKmWzxnCAnJ
      POSTGRES_DB: railway
    ports:
      - "5432:5432"  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  
